# install:
#  pip3 install pre-commit
# run:
#  pre-commit run -a
# update deps:
#  pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # see https://github.com/pre-commit/pre-commit-hooks
      # - id: check-added-large-files
      #   args: ['--maxkb=500']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      # - id: detect-aws-credentials
      - id: detect-private-key
      # conflict with black below
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      # - id: forbid-submodules
      #   args: ['--fix=lf']
      - id: name-tests-test
      # - id: no-commit-to-branch
      #   args: [--branch, staging]
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer
      # - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
      -   id: reorder-python-imports

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.0
    hooks:
      - id: pyupgrade
        # args: ["--py38-plus"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          # NOTE: entries are copy of .flake8-config-file -> for auto-install
          ### Bugs
          - flake8-bugbear
          - flake8-secure-coding-standard
          - flake8-bandit
          - flake8-builtins

          ### Clean Code
          - flake8-comprehensions
          - flake8-simplify
          # - flake8-eradicate
          - flake8-commas

           ### Limitations
          - flake8-blind-except
          - flake8-logging-format
          # - flake8-print

           ### Documentation
          # - flake8-comments
          # - flake8-docstrings
          # - flake8-rst-docstrings

          ### Test-Improvements
#          - flake8-assertive

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: "v0.971"
#    hooks:
#      - id: mypy

#  - repo: https://github.com/codespell-project/codespell
#    rev: "v2.2.2"
#    hooks:
#      - id: codespell



# default_language_version:
#    python: python3.8
