name: Update Maps

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    # deactivated 2023-06-21
    # in UTC -> 21:59 DE time
    # schedule:
    # - cron: "59 19 * * 0"
# TODO
#  push:
#    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  job1:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    steps:
      - name: print start date
        run: |
          date +%Y-%m-%d_%H:%M

      - name: Checkout Repositiry
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Fix ImageMagick cache size problem
        run: |
          sudo cp imagemagick6-policy.xml /etc/ImageMagick-6/policy.xml

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Python cache setup
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-py-cache

      - name: Python install requirements
        run: pip install -r py-requirements.txt

      - name: install Ubuntu packages
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install ghostscript gsfonts ffmpeg > /dev/null

      - name: Generate + zip maps
        run: |
          wget --quiet https://github.com/entorb/COVID-19-Coronavirus-German-Regions/releases/download/data-for-entorb.net/data-json-de.tgz
          mkdir data-json
          tar xfz data-json-de.tgz -C data-json
          python3 plot-de-districts-map.py
          cd maps
          tar cfz ../cache/maps.tgz *.gif *.mp4
          cd ..

      # Publish to release
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: data-for-entorb.net
          prerelease: true
          files: cache/*.tgz

      - name: commit new files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add maps/out/*
          git diff-index --quiet HEAD || git commit -m "auto update"  | grep -v rewrite
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #        force: true
          directory: maps

      - name: print end date
        run: |
          date +%Y-%m-%d_%H:%M
