name: Test Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:

# Initialize
    - name: print start date
      run: |
        date +%Y-%m-%d_%H:%M

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # 0 if you want to push to repo

    - name: Setup environment
      run: |
        cd /usr/share/locales
        sudo ./install-language-pack de_DE.UTF-8

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Python cache setup
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-py-cache

    - name: Python install requirements
      run: pip install -r py-requirements.txt
